# Generated by Django 4.1 on 2024-04-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org_id', to='api.organisation'),
            preserve_default=False,
        ),
    ]
