# Generated by Django 4.1 on 2024-04-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rule_rule_description_rule_rule_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rules_json',
        ),
    ]
