# Generated by Django 4.1 on 2024-04-12 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='queries',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
