# Generated by Django 4.1 on 2024-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_queries_admin_id_queries_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
