# Generated by Django 4.1 on 2024-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_queries_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='query_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
